version: '3'

networks:
  sme-network:
    external: true

services:
###########################################
## MySQL: The database used by SMEAuthenAPI
########################################### 
  authen-db:
    container_name: 10.111.188.10
    image: mariadb:10.4
    networks:
      - sme-network
    restart: always
    command: --default-authentication-plugin=mysql_native_password --character-set-server=utf8 --collation-server=utf8_general_ci
    environment:
      MYSQL_ROOT_PASSWORD: misasme
    volumes:
      - /var/data/mysqlJAVA:/var/lib/mysql
    ports:
    - "13306:3306"
#    - "33060:33060"
###########################################
## RabbitMQ
########################################### 
  rabbit1:
    image: "rabbitmq:3-management"
    networks:
      - sme-network
    hostname: "10.108.179.29"
    restart: always
    environment:
      # RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
      # RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - "5672:5672"
 #     - "15672:15672"
###########################################
## MongoDB
########################################### 
  payment-receipt-db:
    container_name: 10.102.159.118
    image: mongo
    restart: always
    environment:
          - MONGO_DATA_DIR=/data/db
          - MONGO_LOG_DIR=/dev/null
    volumes:
          - /var/data/mongoJAVA:/data/db
    command: mongod --storageEngine wiredTiger --wiredTigerCacheSizeGB 1
    networks:
      - sme-network
    ports:
      - "27117:27017"
