apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: app-ui
  name: app-ui
spec:
  ports:
  - name: "9000"
    port: 9000
    targetPort: 80
  selector:
    io.kompose.service: app-ui
status:
  loadBalancer: {}
