apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: app-ui
  name: app-ui
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: app-ui
    spec:
      containers:
      - image: 10.0.6.27:50000/javateam/java_ui:3.1
        name: ui-container
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
