apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: authent-api
  name: authent-api
spec:
  ports:
  - name: "9001"
    port: 9001
    targetPort: 80
  selector:
    io.kompose.service: authent-api
status:
  loadBalancer: {}
