apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: config-api
  name: config-api
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: config-api
    spec:
      containers:
      - image: 10.0.6.27:50000/javateam/java_config_api:5.3
        name: config-container
        ports:
        - containerPort: 80
        resources: {}
      restartPolicy: Always
status: {}
