version: "2"
networks: 
 sme-network:
  external: true    
services:
  config-api:
    image: 10.0.6.27:50000/javateam/java_config_api:5.1
    container_name: config_container
    build: ./Java.Config/config
    restart: always
    networks:
      - sme-network
    # depends_on:
      # - authen-db
      # - rabbit1
    ports:
      - "9101:80"
#      - "9102:8080"
#########################################
################ Authent
######################################### 
  authent-api:
    image: 10.0.6.27:50000/javateam/java_authent_api:5.1
    container_name: authent_container
    build: ./Java.Authentication/register
    restart: always
    networks:
      - sme-network
    # depends_on:
    #   - authen-db
    #   - rabbit1
    ports:
      - "9001:80"
#      - "9002:8080"

# #########################################
# ################ Payment
# ######################################### 
  payment-api:
    image: 10.0.6.27:50000/javateam/java_payment_api:5.8
    container_name: payment_container
    build: ./Java.PaymentReceiptCQRS/PaymentReceiptCQRS
    restart: always
    networks:
      - sme-network
    # depends_on:
    #   - authen-db
    #   - payment-receipt-db
    #   - rabbit1
    ports:
      - "9003:80"
#      - "9004:8080"
#########################################
################ UI
######################################### 
  app-ui:
    image: 10.0.6.27:50000/javateam/java_ui:5.5
    restart: always
    container_name: ui_container
    build: ./Java.ClientUI
    ports:
      - "9000:80"

