version: "3"
networks: 
 sme-network:
  external: true    
services:
  config-api:
    image: 10.0.6.27:50000/javateam/java_config_api:3.0
    container_name: config_container
    build: ./Java.Config/config
    restart: always
    networks:
      - sme-network
    ports:
      - "9101:80"
#########################################
################ Authent
######################################### 
  authent-api:
    image: 10.0.6.27:50000/javateam/java_authent_api:3.0
    container_name: authent_container
    build: ./Java.Authentication/register
    restart: always
    #mem_limit: 500000000
    #mem_reservation: 300m
    # cpus: 0.5
    # cpu_shares: 73
    # cpuset: 0,1
    networks:
      - sme-network
    ports:
      - "9001:80"
# #########################################
# ################ Payment
# ######################################### 
  payment-api:
    image: 10.0.6.27:50000/javateam/java_payment_api:3.1
    container_name: payment_container
    build: ./Java.PaymentReceiptCQRS/PaymentReceiptCQRS
    restart: always
    networks:
      - sme-network
    ports:
      - "9003:80"
# #########################################
# ################ Report
# ######################################### 
  report-api:
    image: 10.0.6.27:50000/javateam/java_report_api:3.0
    container_name: report_container
    build: ./Java.Report
    restart: always
    networks:
      - sme-network
    ports:
      - "9005:80"
#########################################
################ UI
######################################### 
  app-ui:
    image: 10.0.6.27:50000/javateam/java_ui:3.0
    restart: always
    container_name: ui_container
    build: ./Java.ClientUI
    ports:
      - "9000:80"

