apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: payment-api
  name: payment-api
spec:
  ports:
  - name: "9003"
    port: 9003
    targetPort: 80
  selector:
    io.kompose.service: payment-api
status:
  loadBalancer: {}
